definitions:
  model.CDRJsonResponse:
    properties:
      count:
        type: integer
      data: {}
      status:
        type: string
    type: object
  model.CallCheck:
    properties:
      from_date:
        type: string
      number:
        type: string
      to_date:
        type: string
    type: object
  model.CallHistoryRequest:
    properties:
      destination:
        type: string
      direction:
        type: string
      from_date:
        type: string
      from_number:
        type: string
      from_type:
        type: string
      hangup_by:
        type: string
      has_children:
        type: boolean
      min_talk_sec:
        type: integer
      min_wait_sec:
        type: integer
      number:
        type: string
      queue:
        type: string
      sip_code:
        type: integer
      tag_id:
        type: integer
      team:
        type: string
      to_date:
        type: string
      to_number:
        type: string
      to_type:
        type: string
    type: object
  model.Reload:
    properties:
      reload:
        type: string
    type: object
  model.SwaggerDataResponse:
    properties:
      data:
        items: {}
        type: array
      status:
        type: string
    type: object
  model.SwaggerStandartResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  model.Tag:
    properties:
      name:
        type: string
    type: object
  model.TagInsert:
    properties:
      call_row_id:
        type: integer
      tag_id:
        type: integer
    type: object
info:
  contact: {}
  description: Swagger API for Golang Project MFDC CDR
  title: MFDC CDR API
  version: "1.0"
paths:
  /call/{id}:
    get:
      consumes:
      - application/json
      description: Get one call
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Execute get call
      tags:
      - Calls
  /config/reload:
    get:
      consumes:
      - application/json
      description: Reloading API configuration
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Reload'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Execute reload config
      tags:
      - Reload
  /csc:
    post:
      consumes:
      - application/json
      description: CDR get success call for period
      parameters:
      - description: Call
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.CallCheck'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.SwaggerStandartResponse'
            type: array
      security:
      - ApiKeyAuth: []
      summary: CDR get success call for period
      tags:
      - CDR
  /file/{id}:
    get:
      consumes:
      - application/json
      description: Get file from S3
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Execute get S3
      tags:
      - File
  /list:
    post:
      consumes:
      - application/json
      description: Get a list of all routes with pagination
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 100
        description: Number of routes per page
        in: query
        name: limit
        type: integer
      - description: Provider
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.CallHistoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.CDRJsonResponse'
            type: array
      security:
      - ApiKeyAuth: []
      summary: List CDR
      tags:
      - CDR
  /tags/{id}:
    delete:
      consumes:
      - application/json
      description: Delete tag
      parameters:
      - description: Tag ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.SwaggerStandartResponse'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Delete tag
      tags:
      - Tags
  /tags/add:
    post:
      consumes:
      - application/json
      description: Add new tag
      parameters:
      - description: Tag name
        in: body
        name: tag
        required: true
        schema:
          $ref: '#/definitions/model.Tag'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.SwaggerStandartResponse'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Add tag
      tags:
      - Tags
  /tags/list:
    get:
      consumes:
      - application/json
      description: Tags list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.SwaggerDataResponse'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Tags list
      tags:
      - Tags
  /tags/push:
    put:
      consumes:
      - application/json
      description: Push tag to call
      parameters:
      - description: CallRowID + TagID
        in: body
        name: slice
        required: true
        schema:
          items:
            $ref: '#/definitions/model.TagInsert'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.SwaggerStandartResponse'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Push tag to call
      tags:
      - Tags
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-MFDC-Key
    type: apiKey
swagger: "2.0"
