// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/check-numbers": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает информацию о каждом номере из списка: найден или нет, и дополнительные поля",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Numbers"
                ],
                "summary": "Проверяет наличие номеров в базе данных",
                "parameters": [
                    {
                        "description": "Список номеров для проверки",
                        "name": "numbers",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/function.CheckNumbersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Найденные номера",
                        "schema": {
                            "$ref": "#/definitions/model.JsonResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка в формате запроса",
                        "schema": {
                            "$ref": "#/definitions/model.JsonResponseError"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.JsonResponseError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "function.CheckNumbersRequest": {
            "type": "object",
            "properties": {
                "numbers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.JsonResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "status": {
                    "type": "string"
                }
            }
        },
        "model.JsonResponseError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-MFDC-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "MFDC Number Checker API",
	Description:      "Swagger API for Golang Project MFDC VC",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
