definitions:
  function.CheckNumbersRequest:
    properties:
      numbers:
        items:
          type: string
        type: array
    type: object
  model.JsonResponse:
    properties:
      data: {}
      status:
        type: string
    type: object
  model.JsonResponseError:
    properties:
      error:
        type: string
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  description: Swagger API for Golang Project MFDC VC
  title: MFDC Number Checker API
  version: "1.0"
paths:
  /check-numbers:
    post:
      consumes:
      - application/json
      description: 'Возвращает информацию о каждом номере из списка: найден или нет,
        и дополнительные поля'
      parameters:
      - description: Список номеров для проверки
        in: body
        name: numbers
        required: true
        schema:
          $ref: '#/definitions/function.CheckNumbersRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Найденные номера
          schema:
            $ref: '#/definitions/model.JsonResponse'
        "400":
          description: Ошибка в формате запроса
          schema:
            $ref: '#/definitions/model.JsonResponseError'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/model.JsonResponseError'
      security:
      - ApiKeyAuth: []
      summary: Проверяет наличие номеров в базе данных
      tags:
      - Numbers
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-MFDC-Key
    type: apiKey
swagger: "2.0"
